### ISSUE TITLE
deadlock with debugger step command

### ISSUE THREAD

**Issue by jwestfall69** [yupferris/vb-rs#3]
Using the step command in the debugger will cause a deadlock when it tries to mutex lock the audio driver, because its already being held by the main emulator loop.

Also would you prefer PRs for bugs instead?

**Comment by yupferris** [comment]
Aha, ofc! Nice catch :)

If you wouldn't mind a PR for this would be cool if possible. I don't mind issues or PR's, whatever you'd prefer!

To fix this, passing the `audio_driver` reference to `run_debugger_commands` is probably best, just like `video_driver` currently.

**Comment by jwestfall69** [comment]
Yeah thats what I did in my local copy.
