### ISSUE TITLE
Is the development of this emulator active?

### ISSUE THREAD

**Issue by John-Enigma** [yupferris/vb-rs#32]
I wanna know if the emulator is still active, just to see if all of its games are playable.

**Comment by cbaggers** [comment]
It's still active. @yupferris has just been on a short break making [demos](http://www.pouet.net/prod.php?which=69658) and other cool shiz.

**Comment by yupferris** [comment]
Yes, this project is very much still active. I had announced that I would be taking a break on some other channels; now we're back on track, even with [streaming some of the process](https://www.youtube.com/watch?v=hMo4DQxfbSU) :)
