### ISSUE TITLE
Compatibility chart in README hard to grok

### ISSUE THREAD

**Issue by RandomInsano** [yupferris/vb-rs#34]
TL;DR: I'd like to mush USA and Japan columns together.

I come back randomly to see if anything's changed in compatibility and the split between USA and JP makes it hard to scan, especially when a title doesn't exist in a particular country.

Considering they match 100% of the time, I think it'll be easier for newcomers to scan and understand the compatibility. Notes can be added if USA or JP differ.

Worth it?

**Comment by yupferris** [comment]
Currently the compatibility is the same for all regions of a given game, at least what is known. However I don't know if that will always be the case. It is as far as we know for now, but it's entirely possible for different regions of a game to exhibit different compatibility with the emulator, even though we haven't seen that yet. For this reason, I'd like to keep them as separate columns at least until the remaining titles become compatible.

That said, this has been brought up before (not necessarily the USA/JP split, but readability in general), particularly with the use of heart vs broken heart emoji's. So I don't mind having a ticket open for this in the meantime.

**Comment by yupferris** [comment]
Maybe it's helpful enough to fill in the empty slots with a "no" symbol (eg 🚫) might be more clear? The more I think about it the more I'd still like to keep JP/NA separate, if nothing else to remind me what I need to test again when going through them. But perhaps it's the fact that the not working cells are _empty_ that's the real issue here.

**Comment by RandomInsano** [comment]
I’ll give that a try and we can decide collectively.
