### ISSUE TITLE
Last raw pointer in libretro branch

### ISSUE THREAD

**Issue by Shadlock0133** [yupferris/vb-rs#38]
https://github.com/emu-rs/rustual-boy/blob/9c6cc4a4ab183256c6360cada0b0b8ecb49be94b/rustual-boy-core/src/v810.rs#L113

It's probably last raw pointer on libretro branch. It *might* be the cause of deserialization errors.

**Comment by yupferris** [comment]
Thanks for the tip!

Unfortunately this points to memory that's never re-allocated when applying the save state, and thus wouldn't point to old memory or anything, so it should be correct. The issue must be elsewhere.
