### ISSUE TITLE
Can't enter debugger when video frames aren't being generated

### ISSUE THREAD

**Issue by jwestfall69** [yupferris/vb-rs#4]
I'm been messing with getting vb-rs working in linux.  There is something screwy such that the emulated cpu seems to get stuck in a loop and no longer rendering video frames.  When its in the state its not possible to get into the debugger since the F12 check will only happen when there are video frames available.

**Comment by yupferris** [comment]
Hmm, this is odd. Which game(s) are you testing this with? Are you sure it's the emulated CPU? I haven't seen this before, but I recall someone having some issues with minifb on linux at some point.

**Comment by yupferris** [comment]
There shouldn't be any looping logic at all in the cpu atm actually; it should just step and return how many cycles it took to execute the current instr and whether or not a watchpoint was hit.

**Comment by jwestfall69** [comment]
Sorry I mean the game itself is stuck looping on the vb cpu, not your code.  

Every game I have tried under linux seems to be getting stuck in a loop after a couple frames.   I dont have this issue with running vb-rs on my mactop. 

I originally thought I was having minifb issues cause it wasnt accepting any key input, including escape.  But a little debugging shows the emu stopped rendering frames and thus key input was never being checked.  I moved the key input checks outside the if render frame restriction so I can get into the debugger and start poking around.

**Comment by yupferris** [comment]
Yeah that's still pretty odd I think; unless I've missed something the VIP should always be producing frames as long as the emulator itself is running, regardless of any state the emulator could be in: https://github.com/yupferris/vb-rs/blob/master/src/vip/mod.rs#L526

Will be interesting to see what you find out!

**Comment by yupferris** [comment]
It could be that the audio thread isn't actually pulling samples off of the queue, which would mean the emulator isn't stepping. Perhaps there's something fishy going on there? I recall some symptoms that sound similar to what you're describing that came up when I was doing the switch to CPAL.

**Comment by yupferris** [comment]
An easy way to check that is probably to try printing the size of `read_ring_buffer.inner` here: https://github.com/yupferris/vb-rs/blob/master/src/cpal_engine.rs#L91

**Comment by jwestfall69** [comment]
yeah it was related to the cpal.  It has to do with the picked format.  Instead of using next() like you had it I had to pick nth(20), which is this format.

'Format { channels: [FrontLeft, FrontRight], samples_rate: SamplesRate(48000), data_type: I16 }'

Weird thing is picking 19 which was sample rate 44100 didnt work.  The ring buffer would be consumed a handful of times then stop.

**Comment by yupferris** [comment]
Hmm, that's rather strange indeed. Do the basic CPAL examples work on your setup? I know in the emu we really should at least search for a stereo format, but yeah 44.1khz should be just fine with the resampling.

**Comment by jwestfall69** [comment]
Yeah something is up with cpal.  The beep sample only beeps once.  It looks like there is an issue about it https://github.com/tomaka/cpal/issues/142

**Comment by yupferris** [comment]
Aha, I see. Thanks for the help tracking this down!

In the meantime, it's a bit of a shame the emu can't work without audio output for now. I've been thinking about the top-level stuff a bit and how I want that to fit together; writing up a gist for the steps I want to take to fix all that, which I'll likely execute tomorrow, though bits of it may not work. I'll link that here in a sec.

**Comment by yupferris** [comment]
Braindumped about arch here: https://gist.github.com/yupferris/b476763839094998c91ddb9ecc758984

But tl;dr (and most relevant for this issue) is basically: in the next couple days I'll be able to throw around enough stuff so at least we can easily make a local build without relying on audio :)

**Comment by yupferris** [comment]
Ended up implementing this stuff already :)

I didn't go so far as to implement any other `AudioBufferSink`s or `TimeSource`s, but a null audio sink and time source based on `time::precise_time_ns` should be trivial to make, which should help you test without audio at least if you're interested.

**Comment by jwestfall69** [comment]
Cool I will check it out

**Comment by jwestfall69** [comment]
I've been messing with it and its running a lot slower then real time, but  cpu usage is only 15-20%.

While looking into it I did find one weird thing, but it doesnt seem to effect my slowness.  When you setup the ring buffer the vec! is filling it with 0x0 data, which is then getting processed by cpal's event loop and pushed to the sound card.  This in turn is increasing the samples_read even though they arent real samples.  

This seems to cause a side effect that seeds the calculated target_emulated_cycles during the first time through the emulators main while loop, which allows the inner while loop with the step() function to even run in the beginning.

'''
let target_emulated_time_ns = self.time_source.time_ns() - self.time_source_start_time_ns;
let target_emulated_cycles = target_emulated_time_ns / CPU_CYCLE_TIME_NS;
'''

It looks like you tried to get around the vec! stuff with self.time_source_start_time_ns, but this seems kinda bugged too.   If all the bogus vec! frames got pushed to the soundcard before the main emu while loop starts you will end up with self.time_source.time_ns()  and self.time_source_start_time_ns being the same value causing target_emulated_cycles to be 0.  

Also as a test I added a time_avail_ns() function to the time_source which returns the number of available ns worth of audio fames the ring buffer can still handle.  Then used that to calculate the number of cycle that can be run without filling the ring buffer completely.  Doing this did fix my slowness, but I realize this isnt what you are trying to accomplish.

**Comment by yupferris** [comment]
Aha, interesting. So the idea of the sample preload was to fill the buffer initially to allow for some headroom with the desired latency, so as far as the timer is concerned I think those should still be counted. It may have been a mistake though not to count samples read when the ringbuffer is empty though, as that would stop the time source from ticking. I think that logic needs some work.

The start time stuff is unrelated to the sample preload. I meant for a given time source's `time_ns` to behave like `time::precise_time_ns` where it yields number of ns from an unspecified epoch, so the emulator should not assume it will always start at 0. It's interesting that it ended up causing problems but I think that points to logic errors in `CpalDriver` rather than the interface.

Counting samples read from the buffer for the timer was an attempt to get around the case where you drag the window (on some platforms), where emulation would then be paused for a moment but the time source would still move forward. When you stop dragging the emulator will spit out a bunch of samples all of a sudden, but they will be played at normal speed, so suddenly the audio has enormous latency. I think the problem here is actually that the audio buffer is not an actual ring buffer anymore, so many of the assumptions I made are wrong. Converting that to a fixed size ring buffer again and using samples read from that buffer as a time source should be stable, although it will have the side-effect that when dragging the window the ring buffer's contents will be played over and over, but that's fine I think. Otherwise we'd need to detect window interaction and pause/restart the driver, and I don't think we need to complicate things more.

**Comment by yupferris** [comment]
I've just pushed an implementation for this, which just swaps the `VecDeque` in `CpalDriver` with a proper ring buffer, and it appears to run a lot more consistently (than ever before actually) on my macbook at least (haven't tested other systems yet). Would you mind trying it out now and seeing how it goes?

**Comment by yupferris** [comment]
(granted the emu is still pretty slow on mac right now, but it appears to be much more stable than I've seen it before, and increasing the desired latency in `main` appears to at least fix the resulting clicks/pops as expected)

**Comment by yupferris** [comment]
There _was_ an unintended consequence to this; that is, when the debugger is running, the time source is still ticking, so when exiting the debugger the emu will have to catch up for some time (depending on how much time was spent in the debugger). So, we'll probably need the ability to pause/resume the timing source (timing source as it may not be the same as the audio output in all cases) for that case anyways, which will be good as it would actually make the debugger silent again (currently it ends up repeating the buffer contents over and over).

Alternatively, it's likely possible to produce blank audio frames and simulate pause at the top-level by faking some of the timing var's like `time_source_start_time_ns`, but I'm not sure if that's a better approach or not. It probably is though given the two options of "poisoning the time source interface with pause/resume" (which is weird for a time source) or "slightly complicating the top-level logic" where the debugger is a special-case anyways. Need to think about it some more.

**Comment by jwestfall69** [comment]
Gave it a quick try before work.  Its working good for me too.

**Comment by yupferris** [comment]
Awesome, thanks again :)

**Comment by yupferris** [comment]
Closing this as the original issue was solved. There's still the known issue of the emu not handling time properly when the debugger is activated/deactivated, but that's separate.
