### ISSUE TITLE
Usable in a modern VR headset?

### ISSUE THREAD

**Issue by brian8267** [yupferris/vb-rs#42]
Is it possible to use rustual-boy with a modern VR headset such as the HTC Vive and experience the 3D effects appropriately?

**Comment by yupferris** [comment]
The current UI does not have support for this. The in-progress libretro core leans on retroarch/other frontends to implement this, but the emulator core itself should in theory be compatible.

That said, this is not a project that anybody is actively working on atm, so it may be a while :)
